-- CreateTable
CREATE TABLE "SIGAA_ALUNO" (
    "MATRICULA" VARCHAR(9) NOT NULL,
    "NOME" VARCHAR(80) NOT NULL,

    CONSTRAINT "SIGAA_ALUNO_pkey" PRIMARY KEY ("MATRICULA")
);

-- CreateTable
CREATE TABLE "SIGAA_CURRICULO" (
    "ID" VARCHAR(7) NOT NULL,
    "STATUS" VARCHAR(1),
    "PERIODO_LETIVO_VIGOR" VARCHAR(5) NOT NULL,
    "CARGA_HORARIA_MINIMA_TOTAL" DECIMAL(5,0) NOT NULL,
    "CARGA_HORARIA_MINIMA_OPT" DECIMAL(5,0) NOT NULL,
    "CARGA_HORARIA_OBR" DECIMAL(5,0) NOT NULL,
    "CARGA_HORARIA_ELETIVA_MAX" DECIMAL(5,0) NOT NULL,
    "CARGA_HORARIA_MAX_PERIODO" DECIMAL(5,0) NOT NULL,
    "NUM_PERIODOS" DECIMAL(2,0) NOT NULL,
    "MIN_PERIODOS" DECIMAL(2,0) NOT NULL,
    "MAX_PERIODOS" DECIMAL(2,0) NOT NULL,

    CONSTRAINT "SIGAA_CURRICULO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_CURSO" (
    "ID" VARCHAR(4) NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,
    "GRAU_ACADEMICO" VARCHAR(15) NOT NULL,
    "TURNO" VARCHAR(10) NOT NULL,
    "MODALIDADE" VARCHAR(25) NOT NULL,
    "COORDENADOR" VARCHAR(100),

    CONSTRAINT "SIGAA_CURSO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_DISCIPLINA" (
    "ID" VARCHAR(7) NOT NULL,
    "NOME" VARCHAR(100),
    "MODALIDADE" VARCHAR(50),
    "CARGA_HORARIA_TEORICA" DECIMAL(3,0),
    "CARGA_HORARIA_PRATICA" DECIMAL(3,0),
    "UNIDADE" VARCHAR(3) NOT NULL,

    CONSTRAINT "SIGAA_DISCIPLINA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_MATRICULA" (
    "ID" SERIAL NOT NULL,
    "ALUNO_CURSO" INTEGER NOT NULL,
    "TURMA" INTEGER NOT NULL,
    "STATUS" VARCHAR(3) NOT NULL,
    "PRIORIDADE" DECIMAL(2,0),

    CONSTRAINT "SIGAA_MATRICULA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_MATRICULA_HISTORICO" (
    "ID" SERIAL NOT NULL,
    "ALUNO_CURSO" INTEGER NOT NULL,
    "STATUS" VARCHAR(3) NOT NULL,
    "TURMA" INTEGER NOT NULL,
    "PRIORIDADE" DECIMAL(2,0),
    "DATA_HORA" TIMESTAMPTZ(6),

    CONSTRAINT "SIGAA_MATRICULA_HISTORICO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_MATRICULA_STATUS" (
    "ID" VARCHAR(3) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL,

    CONSTRAINT "SIGAA_MATRICULA_STATUS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_PREREQ" (
    "DISCIPLINA_REQUER" VARCHAR(7) NOT NULL,
    "DISCIPLINA_REQUERIDO" VARCHAR(7) NOT NULL,

    CONSTRAINT "SIGAA_PREREQ_pkey" PRIMARY KEY ("DISCIPLINA_REQUER","DISCIPLINA_REQUERIDO")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_ALUNO_CURSO" (
    "ID" SERIAL NOT NULL,
    "ALUNO" VARCHAR(9) NOT NULL,
    "CURSO" VARCHAR(4) NOT NULL,
    "CURRICULO" VARCHAR(7) NOT NULL,
    "DATA_REGISTRO" DATE NOT NULL,
    "PERIODO_LETIVO_REGISTRO" VARCHAR(5) NOT NULL,
    "STATUS" VARCHAR(1),
    "IRA" REAL,

    CONSTRAINT "SIGAA_RL_ALUNO_CURSO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_ALUNO_CURSO_DISCIPLINA" (
    "ALUNO_CURSO" INTEGER NOT NULL,
    "DISCIPLINA" VARCHAR(7) NOT NULL,
    "PERIODO_LETIVO" VARCHAR(5) NOT NULL,
    "MENCAO" VARCHAR(2),

    CONSTRAINT "SIGAA_RL_ALUNO_CURSO_DISCIPLINA_pkey" PRIMARY KEY ("ALUNO_CURSO","DISCIPLINA","PERIODO_LETIVO")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_CURRICULO_CURSO" (
    "CURRICULO" VARCHAR(7) NOT NULL,
    "CURSO" VARCHAR(4) NOT NULL,

    CONSTRAINT "SIGAA_RL_CURRICULO_CURSO_pkey" PRIMARY KEY ("CURRICULO","CURSO")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_CURRICULO_DISCIPLINA" (
    "CURRICULO" VARCHAR(7) NOT NULL,
    "DISCIPLINA" VARCHAR(7) NOT NULL,
    "PERIODO" DECIMAL(2,0),
    "TIPO" VARCHAR(15) NOT NULL,

    CONSTRAINT "SIGAA_RL_CURRICULO_DISCIPLINA_pkey" PRIMARY KEY ("CURRICULO","DISCIPLINA")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_CURSO_UNIDADE" (
    "CURSO" VARCHAR(4) NOT NULL,
    "UNIDADE" VARCHAR(3) NOT NULL,

    CONSTRAINT "SIGAA_RL_CURSO_UNIDADE_pkey" PRIMARY KEY ("CURSO","UNIDADE")
);

-- CreateTable
CREATE TABLE "SIGAA_RL_TURMA_HORARIOAULA" (
    "TURMA" INTEGER NOT NULL,
    "HORARIOAULA" VARCHAR(2) NOT NULL,

    CONSTRAINT "SIGAA_RL_TURMA_HORARIOAULA_pkey" PRIMARY KEY ("TURMA","HORARIOAULA")
);

-- CreateTable
CREATE TABLE "SIGAA_TURMA" (
    "ID" SERIAL NOT NULL,
    "CODIGO" VARCHAR(2) NOT NULL,
    "PERIODO_LETIVO" VARCHAR(5) NOT NULL,
    "DISCIPLINA" VARCHAR(7) NOT NULL,
    "VAGAS" DECIMAL(3,0),
    "SEDE" VARCHAR(50),

    CONSTRAINT "SIGAA_TURMA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_TURMA_HORARIOAULA" (
    "ID" VARCHAR(3) NOT NULL,
    "DIA" VARCHAR(3) NOT NULL,
    "HORA_INICIO" VARCHAR(5) NOT NULL,
    "HORA_FIM" VARCHAR(5) NOT NULL,

    CONSTRAINT "SIGAA_TURMA_HORARIOAULA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SIGAA_UNIDADE" (
    "ID" VARCHAR(3) NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,

    CONSTRAINT "SIGAA_UNIDADE_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_ALUNO" ON "SIGAA_ALUNO"("MATRICULA");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_CURRICULO" ON "SIGAA_CURRICULO"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_CURSO" ON "SIGAA_CURSO"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_DISCIPLINA" ON "SIGAA_DISCIPLINA"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_MATRICULA" ON "SIGAA_MATRICULA"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_MATRICULA_HISTORICO" ON "SIGAA_MATRICULA_HISTORICO"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "ALUNO_CURSO_UNIQUE" ON "SIGAA_RL_ALUNO_CURSO"("ALUNO", "CURSO", "PERIODO_LETIVO_REGISTRO");

-- CreateIndex
CREATE UNIQUE INDEX "TURMA_HAULA_UNIQUE" ON "SIGAA_RL_TURMA_HORARIOAULA"("HORARIOAULA", "TURMA");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_TURMA" ON "SIGAA_TURMA"("ID");

-- CreateIndex
CREATE UNIQUE INDEX "TURMA_UNIQUE" ON "SIGAA_TURMA"("CODIGO", "PERIODO_LETIVO", "DISCIPLINA");

-- CreateIndex
CREATE UNIQUE INDEX "HORARIOAULA_UNIQUE" ON "SIGAA_TURMA_HORARIOAULA"("DIA", "HORA_INICIO", "HORA_FIM");

-- CreateIndex
CREATE UNIQUE INDEX "PK_SIGAA_UNIDADE" ON "SIGAA_UNIDADE"("ID");

-- AddForeignKey
ALTER TABLE "SIGAA_DISCIPLINA" ADD CONSTRAINT "FK_UNIDADE" FOREIGN KEY ("UNIDADE") REFERENCES "SIGAA_UNIDADE"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_MATRICULA" ADD CONSTRAINT "FK_ALUNO_CURSO" FOREIGN KEY ("ALUNO_CURSO") REFERENCES "SIGAA_RL_ALUNO_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_MATRICULA" ADD CONSTRAINT "FK_MATRICULA_STATUS" FOREIGN KEY ("STATUS") REFERENCES "SIGAA_MATRICULA_STATUS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_MATRICULA" ADD CONSTRAINT "FK_TURMA" FOREIGN KEY ("TURMA") REFERENCES "SIGAA_TURMA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_MATRICULA_HISTORICO" ADD CONSTRAINT "FK_ALUNO_CURSO" FOREIGN KEY ("ALUNO_CURSO") REFERENCES "SIGAA_RL_ALUNO_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_MATRICULA_HISTORICO" ADD CONSTRAINT "FK_MATRICULA_STATUS" FOREIGN KEY ("STATUS") REFERENCES "SIGAA_MATRICULA_STATUS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_PREREQ" ADD CONSTRAINT "FK_DISCIPLINA_REQUER" FOREIGN KEY ("DISCIPLINA_REQUER") REFERENCES "SIGAA_DISCIPLINA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_PREREQ" ADD CONSTRAINT "FK_DISCIPLINA_REQUERIDO" FOREIGN KEY ("DISCIPLINA_REQUERIDO") REFERENCES "SIGAA_DISCIPLINA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_ALUNO_CURSO" ADD CONSTRAINT "FK_ALUNO" FOREIGN KEY ("ALUNO") REFERENCES "SIGAA_ALUNO"("MATRICULA") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_ALUNO_CURSO" ADD CONSTRAINT "FK_CURRICULO" FOREIGN KEY ("CURRICULO") REFERENCES "SIGAA_CURRICULO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_ALUNO_CURSO" ADD CONSTRAINT "FK_CURSO" FOREIGN KEY ("CURSO") REFERENCES "SIGAA_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_ALUNO_CURSO_DISCIPLINA" ADD CONSTRAINT "FK_ALUNO_CURSO" FOREIGN KEY ("ALUNO_CURSO") REFERENCES "SIGAA_RL_ALUNO_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_ALUNO_CURSO_DISCIPLINA" ADD CONSTRAINT "FK_DISCIPLINA" FOREIGN KEY ("DISCIPLINA") REFERENCES "SIGAA_DISCIPLINA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURRICULO_CURSO" ADD CONSTRAINT "FK_CURRICULO" FOREIGN KEY ("CURRICULO") REFERENCES "SIGAA_CURRICULO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURRICULO_CURSO" ADD CONSTRAINT "FK_CURSO" FOREIGN KEY ("CURSO") REFERENCES "SIGAA_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURRICULO_DISCIPLINA" ADD CONSTRAINT "FK_CURRICULO" FOREIGN KEY ("CURRICULO") REFERENCES "SIGAA_CURRICULO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURRICULO_DISCIPLINA" ADD CONSTRAINT "FK_DISCIPLINA" FOREIGN KEY ("DISCIPLINA") REFERENCES "SIGAA_DISCIPLINA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURSO_UNIDADE" ADD CONSTRAINT "FK_CURSO" FOREIGN KEY ("CURSO") REFERENCES "SIGAA_CURSO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_CURSO_UNIDADE" ADD CONSTRAINT "FK_UNIDADE" FOREIGN KEY ("UNIDADE") REFERENCES "SIGAA_UNIDADE"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_TURMA_HORARIOAULA" ADD CONSTRAINT "FK_HORARIOAULA" FOREIGN KEY ("HORARIOAULA") REFERENCES "SIGAA_TURMA_HORARIOAULA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_RL_TURMA_HORARIOAULA" ADD CONSTRAINT "FK_TURMA" FOREIGN KEY ("TURMA") REFERENCES "SIGAA_TURMA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SIGAA_TURMA" ADD CONSTRAINT "FK_DISCIPLINA" FOREIGN KEY ("DISCIPLINA") REFERENCES "SIGAA_DISCIPLINA"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
